TEST: banned function

diff --git a/.github/workflows/libprint.a.yml b/.github/workflows/libprint.a.yml
--- a/.github/workflows/libprint.a.yml
+++ b/.github/workflows/libprint.a.yml
@@ -31,3 +31,26 @@ jobs:
           fi
           echo "::notice title=Marvin :: No coding style error detected."
           exit 0
+  banning_functions_checker:
+    name: Banned functions checker
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Run coding style
+        run: check.sh $(pwd) $(pwd)
+      - name: Display style errors
+        run: |
+          make tests
+          have_error=0;
+          while read line; do IFS=':' read -ra CODING <<< "$line";
+              echo "::error file=${CODING[0]},line=${CODING[2]},title=${CODING[1]} banned function::are used";
+              have_error=1;
+          done < banned-functions-reports.log
+          if [[ $have_error -eq 1 ]]; then
+            exit 1
+          fi
+          echo "::notice title=Marvin :: No banned functions detected."
+          exit 0
